name: Deploy to 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 构建代码
      - name: Build
        run: yarn install --frozen-lockfile && yarn build

      # 创建一个新的 Release
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
        with:
          owner: Zhang-Wei-666
          repo: test2
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
