name: Deploy to Test3

on:
  release:
    types: ['released']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      # 构建代码
      - name: Build
        run: yarn install --frozen-lockfile && yarn build

      - name: Commit
        run: |
          cd dist
          git init
          git config user.email "994039348@qq.com"
          git config user.name "Zhang-Wei-666"
          git add .
          git commit -m "update"
          
      - name: Push
        uses: ad-m/github-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
        with:
          github_token: ${{ secrets.TEST_TOKEN }}
          repository: Zhang-Wei-666/test2
          force: true

      # 创建一个新的 Release
#       - name: Release
#         uses: softprops/action-gh-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
#         with:
#           repository: Zhang-Wei-666/test2
#           release_name: v1.0.4
#           tag_name: v1.0.4
