name: Deploy to Test3

on:
  push:
    branches: ['main']
  release:
    types: ['released']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - run: echo branch_protection_rule:${{ github.event.branch_protection_rule }}
      - run: echo check_run:${{ github.event.check_run }}
      - run: echo check_suite:${{ github.event.check_suite }}
      - run: echo create:${{ github.event.create }}
      - run: echo delete:${{ github.event.delete }}
      - run: echo deployment:${{ github.event.deployment }}
      - run: echo deployment_status:${{ github.event.deployment_status }}
      - run: echo discussion:${{ github.event.discussion }}
      - run: echo discussion_comment:${{ github.event.discussion_comment }}
      - run: echo fork:${{ github.event.fork }}
      - run: echo gollum:${{ github.event.gollum }}
      - run: echo issue_comment:${{ github.event.issue_comment }}
      - run: echo issues:${{ github.event.issues }}
      - run: echo label:${{ github.event.label }}
      - run: echo milestone:${{ github.event.milestone }}
      - run: echo page_build:${{ github.event.page_build }}
      - run: echo project:${{ github.event.project }}
      - run: echo project_card:${{ github.event.project_card }}
      - run: echo project_column:${{ github.event.project_column }}
      - run: echo public:${{ github.event.public }}
      - run: echo pull_request:${{ github.event.pull_request }}
      - run: echo push:${{ github.event.push }}
      - run: echo registry_package:${{ github.event.registry_package }}
      - run: echo release:${{ github.event.release }}
      - run: echo status:${{ github.event.status }}
      - run: echo watch:${{ github.event.watch }}
      - run: echo workflow_run:${{ github.event.workflow_run }}

      # 构建代码
#       - name: Build
#         run: yarn install --frozen-lockfile && yarn build

#       - name: Commit
#         run: |
#          cd dist
#          git init
#          git config user.email "994039348@qq.com"
#          git config user.name "Zhang-Wei-666"
#          git add .
#          git commit -m "update"

#       - name: Push
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.TEST_TOKEN }}
#           repository: Zhang-Wei-666/test2
#           directory: dist
#           force: true

      # 创建一个新的 Release
#       - name: Release
#         uses: softprops/action-gh-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
#         with:
#           repository: Zhang-Wei-666/test2
#           release_name: v${{ github.ref }}
#           tag_name: v1.0.4
