name: Deploy to Test3

on:
  release:
    types: ['released']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 构建代码
      # - name: Build
      #   run: yarn install --frozen-lockfile && yarn build

      # 创建一个新的 Release
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
        with:
          repository: Zhang-Wei-666/test2
          release_name: v1.0.1
          tag_name: v1.0.1
