name: Deploy to Test2

on:
  release:
    types: ['released']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      # 构建代码
      - name: Build
        run: |
          npm install pnpm -g
          pnpm build

      # 提交打包后的代码
      - name: Commit
        run: |
         cd dist
         git init
         git config user.email "994039348@qq.com"
         git config user.name "Zhang-Wei-666"
         git add .
         git commit -m "update"

      # 推送打包后的代码到指定存储库
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TEST_TOKEN }}
          repository: Zhang-Wei-666/test2
          directory: dist
          force: true

      # 在指定存储库发布一个版本
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
        with:
          repository: Zhang-Wei-666/test2
          name: ${{ github.event.release.name }}
          tag_name: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
