name: Deploy to 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 构建代码
      - name: Build
        run: yarn install --frozen-lockfile && yarn build

      # 创建一个新的 Release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TEST_TOKEN }}
